version: .{build}

init:
- ps: $commit = $env:appveyor_repo_commit.SubString(0,7)
- ps: $timestamp = $env:appveyor_repo_commit_timestamp.SubString(0,10)
- ps: Update-AppveyorBuild -Version "$env:appveyor_repo_branch-$commit-$timestamp"


#- ps: Update-AppveyorBuild -Version "$env:appveyor_repo_branch-$env:appveyor_repo_commit-$env:appveyor_repo_commit_timestamp"

#branches:
#    only:
#      - master

# clone directory
clone_folder: c:\projects\pvr.hts

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

install:
  - ps: wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-win32-x86.zip -OutFile cmake.zip
  - cmd: echo "Unzipping cmake..."
  - cmd: 7z x cmake.zip -o"C:\Program Files (x86)\" -y > nul
  - cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\Program Files (x86)\cmake-3.0.2-win32-x86\bin
  - cmd: cmake --version
  - cmd: del cmake.zip

environment:
  app_id: pvr.hts

  matrix:
    #- GENERATOR: "Visual Studio 12 2013"
      #CONFIG: Debug

    - GENERATOR: "Visual Studio 12 2013"
      CONFIG: Release

build_script:
  - call "%VS120COMNTOOLS%..\..\VC\bin\vcvars32.bat"
  - set cur_dir=%cd%
  - cd ..
  - git clone --depth=1 https://github.com/xbmc/xbmc.git
  - cd %app_id%
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -DADDONS_TO_BUILD=%app_id% -DCMAKE_BUILD_TYPE=%CONFIG% -DADDON_SRC_PREFIX=../.. -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/project/cmake/addons
  - cmake --build "%cur_dir%\build" --target %app_id%